### ISSUE TITLE
Missing timeout

### ISSUE THREAD

**Issue by ways** [mercator-ocean/copernicus-marine-toolbox#109]
## Motivation

In our application https://opendrift.github.io/ copernicusmarine is used as one of several sources. This bug causes the application to stall instead of using other sources.

## Expected behavior

A default timeout should be set, and should be overridable.

## Actual behavior

Copernicusmarine doesn't set timeout for network requests. When the object store is down, this causes the module to wait forever. 

## Steps to reproduce

- Open netcat to listen on a port, but not respond: sudo nc -v -l 443
- Point all object store addresses to this machines IP, using the hosts file.

> $ tail /etc/hosts
> 157.249.79.36 s3.waw3-1.cloudferro.com
> 157.249.79.36 cloudferro.com
> 157.249.79.36 *.cloudferro.com

Run `copernicusmarine describe` and notice that it will wait indefinitely.

## Environment

Operating System: Ubuntu 22.04 64-bit
Python version: Python 3.10.12
copernicusmarine version: 1.2.4
Source execution: terminal
RAM: 32 GB
Bandwidth: Gigabit network
Use of proxy: no
Use of VPN: no
Date: There was a cloud outage 06.08.2024 which surfaced these problems.
Network Permission: No limitations on network.

**Comment by ways** [comment]
Simply setting a timeout in aiohttp doesn't create a nice result, but at least it aborts the program instead of hanging. Any suggestions on how this should work?

```
root@1b949c7c84a7:/app# copernicusmarine describe 
Fetching catalog:   0%|                                                                                                                                                                                                                           | 0/3 [00:00<?, ?it/s]Setting timeout 2s
ERROR - 2024-08-08T15:18:41Z - Unexpected error while downloading: '>' not supported between instances of 'str' and 'int'
ERROR - 2024-08-08T15:18:41Z - Type error: '>' not supported between instances of 'str' and 'int'
Fetching catalog:   0%|                                                                                                                                                                                                                           | 0/3 [00:00<?, ?it/s]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x774c3e5bb500>

```

**Comment by renaudjester** [comment]
Hi @ways thanks for raising this issue and thanks even more for your pull request. 

This seems to be a great idea! A few things: 

1) If I get it well, the problem comes from the fact that the code is hanging indefinitely whereas you would like it to throw an error. I can see in the PR that you talk only about the aiohttp, do you know if we would have the same problem with request or boto3 (used in the get and subset)? They might have some timeout already. 

2) We are currently working on a v2 of the toolbox. Maybe I would integrate this into the v2 roadmap as it sets a default value (see branch `copernicusmarine-toolbox-v2`). 

Thanks again!

**Comment by ways** [comment]
> Hi @ways thanks for raising this issue and thanks even more for your pull request.
> 
> This seems to be a great idea! A few things:
> 
>     1. If I get it well, the problem comes from the fact that the code is hanging indefinitely whereas you would like it to throw an error. I can see in the PR that you talk only about the aiohttp, do you know if we would have the same problem with request or boto3 (used in the get and subset)? They might have some timeout already.

I've added the timeout to request now.

I am unfamiliar with boto3. I think it's better if someone familiar with it tests if we need similar changes there.

>     2. We are currently working on a v2 of the toolbox. Maybe I would integrate this into the v2 roadmap as it sets a default value (see branch `copernicusmarine-toolbox-v2`).

In my opinion this is important enough to include before v2. The timeout can be set to something very high (900 seconds?), to not affect current users.

**Comment by renaudjester** [comment]
I just checked it out and it seems that for boto3 the timeouts are 60 seconds by default: https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html

**Comment by renaudjester** [comment]
Closing it as it has been done here: https://github.com/mercator-ocean/copernicus-marine-toolbox/pull/146

I'll let you check if it fits you (in pre-release >=2.0.0a2 or release >=2.0.0)

Thanks for taking the time and giving the idea!
