### ISSUE TITLE
using aiohttp version 3.10 results in crash when running copernicusmarine.describe()

### ISSUE THREAD

**Issue by thopri** [mercator-ocean/copernicus-marine-toolbox#125]
copernicusmarine.describe() does not work with aiohttp version 3.10. It crashes with an error saying "no running event loop"

I have managed to get around the error by downgrading back to 3.9, as follows:

```shell
$ conda install aiohttp=3.9.*
```

**Comment by thopri** [comment]
Edit, although I notice I am on version 1.3 not 1.3.3 so this may already be fixed? Will update and close if so.

**Comment by uriii3** [comment]
actually we restricted the aiohttp version, I think it still doesn't work with `aiohttp>=3.10.0` but the fix is on our roadmap.

**Comment by thopri** [comment]
I figured out it was due to copernicusmarine being listed first in my environment.yml, so it installs correctly at this point. Then another dependency changed aiohttp to 3.10. Listing copernicusmarine last builds my environment correctly but I don't think the order should really matter? anyway not an copernicusmarine problem at least!

**Comment by renaudjester** [comment]
Thanks for opening the issue @thopri! As @uriii3 said, the toolbox does not support `aiohttp>=3.10.0` 

We are currently working on the version 2 of the toolbox where we will take care of this so the constraint should be relaxed for the future versions of the toolbox
