### ISSUE TITLE
Add logging about where to register for credentials

### ISSUE THREAD

**Issue by veenstrajelmer** [mercator-ocean/copernicus-marine-toolbox#139]
When using copernicusmarine in Python, it is not clear which user/pass to provide. This is especially an issue if copernicusmarine is embedded in a larger workflow. If as part of that workflow the `copernicusmarine.login()` function is called and the user is not yet logged in, they will get:
```
username: 
```

It would be great if this is preceded by a line like `"Downloading CMEMS data requires a Copernicus Marine username and password, sign up for free at: https://data.marine.copernicus.eu/register."`

**Comment by uriii3** [comment]
Mmh, yes, it would actually make sense! Thanks for the recommendation!

**Comment by uriii3** [comment]
Thanks for all the feedback, closing this one!

**Comment by veenstrajelmer** [comment]
Thanks a lot for following up on this issue so quick, amazing! I do notice it has been merged into the v2 branch and not in main. What is the timeline for v2 to be released? Just for some expectation management.

**Comment by uriii3** [comment]
Yeees! We are planning to do a pre-release next week. The main release for v2 will be October-November but time is always a bit relative.
Hope this helps!
