### ISSUE TITLE
v2.0.0a2 ERROR Unbound local error: cannot access local variable 'thumbnail_url' where it is not associated with a value

### ISSUE THREAD

**Issue by jdemaria** [mercator-ocean/copernicus-marine-toolbox#173]
Hi,

We are a CMEMS PU and we try to upgrade to 2.0.0a2 (from 1.2.3), and facing this error:
to reproduce :
```
copernicusmarine describe
WARNING - 2024-10-17T14:46:21Z - Using a pre-release or a non-official version of the client. Client version: 2.0.0a2
ERROR - 2024-10-17T14:46:30Z - Unbound local error: cannot access local variable 'thumbnail_url' where it is not associated with a value

```
with --log-level DEBUG I also see a lot of messages like "Service not handled: downsampled4, platforms" but I don't know if it's related.

I installed the toolbox using this micromamba env.yml:
```
name: cmt
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - copernicusmarine>=2.0.0a0
  - python>=3.9,<=3.12
  - s5cmd
  - awscli
```

Thanks,
Julien

**Comment by jdemaria** [comment]
or do you recommend that we use 2.0.0a1 in the meantime if not impacted by this bug?

**Comment by renaudjester** [comment]
Hi @jdemaria!

I wouldn't advise using 2.0.0a1! 

Indeed we noticed this problem in the release and we plan to make a new prerelease (2.0.0a3) with this fix in the next few days (if not today). 

It shouldn't impact the `get` and `subset` commands (except for the dataset missing this "thumbnail_url" of course)

**Comment by jdemaria** [comment]
Ok thanks @renaudjester I will wait for the new prerelease because we need the describe command (we use it to find the S3 bucket address for our datasets).

**Comment by uriii3** [comment]
The pre-release 2.0.0.a3 is already available, with this specific bug corrected.

Hope this helps!
