### ISSUE TITLE
Wave dataset not working

### ISSUE THREAD

**Issue by AchrefAO** [mercator-ocean/copernicus-marine-toolbox#210]
Hi, I'm wondering why the following wave datasets are not working with the toolbox:

1. dataset-wam-arctic-1hr3km-be
2. cmems_mod_arc_wav_my_3km_PT1H-i

I tried these lines in python:

>>> import copernicusmarine
>>> d = copernicusmarine.open_dataset(dataset_id='cmems_mod_arc_wav_my_3km_PT1H-i')

**Comment by uriii3** [comment]
Hello, I think currently we don't support the `subset` (and subsequently `open_dataset`) for this datasets, check: [this link](https://data.marine.copernicus.eu/product/ARCTIC_MULTIYEAR_WAV_002_013/notifications). In the last incident, it is specified that this dataset (and others) are not yet available.

You can access that dataset with the `get` command for the moment to download the original files.

We will be developing the `subset` command to be able to handle those in the next sprints.

For the moment, as said before, try: 
```
import copernicusmarine

d = copernicusmarine.get(
    dataset_id="cmems_mod_arc_wav_my_3km_PT1H-i",
)
``` 
(filter them as you like, those contain a lot of data!)
