### ISSUE TITLE
open_dataset failed when no dataset_version specified

### ISSUE THREAD

**Issue by quai20** [mercator-ocean/copernicus-marine-toolbox#227]
This fails, with `NoServiceAvailable` Exception from `_get_first_available_service_type`. But I'm pretty sure this was working some time ago : 
```
ds = cm.open_dataset(
    dataset_id = 'cmems_obs-ins_glo_phy-temp-sal_nrt_oa_P1M',    
    minimum_longitude = -30,
    maximum_longitude = 0,
    minimum_latitude = 35,
    maximum_latitude = 50,
    start_datetime = '2024-10-01',
    end_datetime = '2024-10-01',
    variables = ['TEMP','PSAL'],
    minimum_depth = -1,
    maximum_depth = -1
    )
```
---
This works, with the `dataset_version` specified : 
```
ds = cm.open_dataset(
    dataset_id = 'cmems_obs-ins_glo_phy-temp-sal_nrt_oa_P1M',
    dataset_version = "202211",
    minimum_longitude = -30,
    maximum_longitude = 0,
    minimum_latitude = 35,
    maximum_latitude = 50,
    start_datetime = '2024-10-01',
    end_datetime = '2024-10-01',
    variables = ['TEMP','PSAL'],
    minimum_depth = -1,
    maximum_depth = -1
    )
```

**Comment by fmarzocca** [comment]
I am using the same call as yours, but instead of `cm.open_dataset`, I am using `cm.subset`, with no errors withiout specifying the version.

**Comment by uriii3** [comment]
Could you specify the version of the `copernicusmarine` toolbox that you are using?

**Comment by quai20** [comment]
> Could you specify the version of the `copernicusmarine` toolbox that you are using?

Oh yes sorry. This is with `1.1.0` version.

**Comment by quai20** [comment]
Updating to `1.3.4` fixed the issue. Thanks !
